version: "3.3"

services:
  app:
    user: root
    build:
      context: ./
      target: dev
    container_name: convert-pdf
    ports:
      - 3002:3002
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - TZ=Asia/Bangkok

volumes:
  src:
    driver: local
