version: "3.3"

services:
  app:
    build:
      context: ./
      target: prod
    container_name: convert-pdf
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - TZ=Asia/Bangkok
    
volumes:
  src:
    driver: local
