version: "3.3"

services:
  app:
    user: root
    build:
      context: .
      target: production
    container_name: html-pdf
    ports:
      - 3002:3002
    volumes:
      - ./public:/app/public   
    environment:
      - TZ=Asia/Bangkok

volumes:
  src:
    driver: local
